### PR TITLE
Refresh Hyperledger Fabric for Trusted IoT

### PR DESCRIPTION
**Pull request by johnwalicki**
Refresh Hyperledger Fabric for Trusted IoT removes the decommissioned Watson IoT Quickstart node, updates all the containers with newer node v14 and packages, adds a env requirement to the deployments. tweaks the documentation.

### CODE REVIEW

**Comment by johnwalicki** [comment]
@ljbennett62  @yigitpolat  Please review.

**Comment by johnwalicki** [comment]
I have added additional commits to this PR.  
Tested on a standard Kubernetes cluster and improved the create-ingress.yaml

**Comment by yigitpolat** [comment]
@johnwalicki thank you very for the contribution. I really liked the new UI.

Everything seems fine and clear except e7f0806. When I sent POST requests to enroll admin and register user I am receiving empty msg.payloads. I checked the rest-api logs and there is an error says "permission denied, mkdir '/app/wallet/admin'". fyi, wallet folder's permissions are as follows: drwxr-xr-x. What would be your comment on this? Should we try to fix the commit or keep the old version?

Besides, Get History function will be fixed with #5

**Comment by johnwalicki** [comment]
Hi Yigit - Thanks for the review. 
- The https://github.com/IBM/Hyperledger-Fabric-for-Trusted-IoT/commit/e7f080602094a102983fec116bd13cc41c69227f commit is now a multi-stage Dockerfile.  It substantially reduces the size of the deployed production image.  The first stage, installs / builds the npm packages and copies only the production results into the production image.  It also adopts Red Hat ubi8 as the base image. 

It definitely works better and is more aligned to deployments into OpenShift (not in this particular case, but I've adopted ubi8 for all my containers as a best practice)

**Comment by johnwalicki** [comment]
I spent a bunch of time understanding the Node-RED flow and how it interacts with the Fabric node.js SDK.  What I found was that you can only initialize the user and contract once. Subsequent attempts required me to bump the user and contract.

May I suggest that you merge #5 and this #11 and I'll run through it again when all the pieces are in master?

**Comment by yigitpolat** [comment]
I don't have permission to merge this. @ljbennett62 I made my comments to open issues and pull requests. Can you take a look and merge the required ones?
@johnwalicki will try to fix the issue about permissions and create a new PR, but first lets merge this PR to master and take a look later on.

**Pull request merged**
